# Generated by Django 5.2.12 on 2026-03-21 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_url', models.URLField(help_text='Target domain (e.g., https://example.com)', max_length=255, unique=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('verification_method', models.CharField(choices=[('DNS', 'DNS TXT Record'), ('FILE', 'File Upload'), ('EMAIL', 'Email Verification')], default='DNS', max_length=10)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
