# Generated by Django 5.2.12 on 2026-03-21 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 score based on vulnerabilities')),
                ('log_output', models.TextField(blank=True, help_text='Terminal-style real-time logs')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='assets.domain')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vuln_type', models.CharField(choices=[('XSS', 'Cross-Site Scripting (XSS)'), ('SQLI', 'SQL Injection (SQLi)'), ('BOLA', 'Broken Object Level Authorization (BOLA)'), ('SSRF', 'Server-Side Request Forgery (SSRF)'), ('OTHER', 'Other Vulnerability')], max_length=10)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('exploit_path', models.TextField(blank=True)),
                ('proof_of_exploit', models.TextField(blank=True)),
                ('ai_explanation', models.TextField(blank=True)),
                ('ai_fix_suggestion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scan')),
            ],
        ),
    ]
