# Generated by Django 6.0.3 on 2026-03-26 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_score', models.FloatField(default=0.0)),
                ('crash_probability', models.FloatField(default=0.0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('vector_signature', models.TextField(blank=True, help_text='Pinecone similarity signature')),
                ('intel_data', models.JSONField(blank=True, default=dict)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='assets.domain')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20)),
                ('test_results', models.TextField(blank=True)),
                ('security_results', models.TextField(blank=True)),
                ('autofix_results', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='assets.domain')),
            ],
        ),
    ]
